### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST https://strong-lynelle-wjmlvbcy-6cdaec0b.koyeb.app/pdptube/auth/sign-up
    Content-Type: application/json

{
  "firstName": "user01",
  "lastName": "user01",
  "email" : "user@gmail.com",
  "password" : "root123",
  "age" : 17
}

###

POST http://localhost:8080/pdptube/auth/signIn
Content-Type: application/json

{
  "email": "sardor@gmail.com",
  "password": "root123"
}

###

GET localhost:8080/pdptube/video
Authorization: ------

###

# 4. `/videos`


    - `POST /video/comment` — Video kommentini yozish uchun to'g'ri yo'l.
    - `POST /video/comment/like` — Kommentga like qo'shish uchun to'g'ri yo'l.
    - `DELETE /video/comment` — Video kommentini o'chirish uchun to'g'ri yo'l.
    - `POST /video/comment/dislike` — Kommentga dislike qo'shish uchun to'g'ri yo'l.
    - `POST /video/comment/reply` — Kommentga javob yozish uchun to'g'ri yo'l.
    - `POST /video/add-to-playlist` — Videoni playlistga qo'shish uchun to'g'ri yo'l.



### 5. `/playlist`
   - `GET /playlist` — Foydalanuvchining playlistlarini olish uchun to'g'ri yo'l.
    - `POST /playlist/add` — Yangi playlist yaratish uchun to'g'ri yo'l.
    - `DELETE /playlist/delete` — Playlistni o'chirish uchun to'g'ri yo'l.
    - `GET /playlist/videos` — Playlistdagi videolarni olish uchun to'g'ri yo'l.
